using Content.Client._ES.Core;
using Content.Client.UserInterface.Controls;
using Content.Shared._ES.Telesci.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Telesci.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESPortalGeneratorConsoleWindow : FancyWindow
{
    public event Action? OnActivatePressed;

    public ESPortalGeneratorConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        ChargeBar.ForegroundStyleBoxOverride = new StyleBoxFlat(Color.Yellow);

        ActivateButton.OnPressed += _ => OnActivatePressed?.Invoke();
    }

    public void Update(ESPortalGeneratorConsoleBuiState state)
    {
        if (state.FinalPhase)
        {
            StatusLabel.UnsafeSetMarkup(Loc.GetString("es-ui-portalgen-console-label-status-final-charging"));
        }
        else if (state.Interrupted)
        {
            StatusLabel.UnsafeSetMarkup(Loc.GetString("es-ui-portalgen-console-label-status-blocked"));
        }
        else
        {
            StatusLabel.UnsafeSetMarkup(state.Charge >= 1
                ? Loc.GetString("es-ui-portalgen-console-label-status-ready")
                : Loc.GetString("es-ui-portalgen-console-label-status-charging"));
        }

        ActivateButton.Disabled = state.Charge < 1 || state.FinalPhase;

        ChargeLabel.UnsafeSetMarkup(Loc.GetString("es-ui-portalgen-console-label-charge-fmt",
            ("charge", (int) (state.Charge * 100))));

        ChargeBar.Value = state.Charge;
    }
}
