- type: job
  id: ESHeadOfPersonnel
  name: ESjob-name-hop
  description: ESjob-description-hop
  playTimeTracker: ESJobHeadOfPersonnel
  startingGear: ESHoPGear
  icon: "JobIconHeadOfPersonnel"
  supervisors: job-supervisors-captain
  canBeAntag: false
  overrideConsoleVisibility: false
  access:
  - Command
  - HeadOfPersonnel
  - Maintenance
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: ESHoPGear
  equipment:
    shoes: ClothingShoesColorBrown
    id: HoPPDA
    ears: ClothingHeadsetAltCommand
    head: ClothingHeadHatHopcap
    belt: BoxFolderClipboardThreePapers
    jumpsuit: ClothingUniformJumpsuitHoP
    back: ClothingBackpack
  storage:
    back:
    - ESBoxSurvival
    - Flash

- type: chameleonOutfit
  id: ESHeadOfPersonnel
  job: ESHeadOfPersonnel
  hidden: false
